spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dna
    username: root
    password: mima
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

python:
  explainer:
    path: "C:\\Users\\silence\\miniconda3\\envs\\torch_1_13_1\\python.exe"
  pretrain-explainer:
    path: "C:\\Users\\silence\\miniconda3\\envs\\hyena-dna\\python.exe"
  pretrain-script:
    path: "C:\\Guo\\Git\\hyena-dna\\train.py"
    get-original-path: "C:\\Guo\\Git\\hyena-dna\\getoriginal.py"
  transfer-script:
    path: "C:\\Guo\\Git\\transfer-dna\\predict1.py"
    get-original-path: "C:\\Guo\\Git\\transfer-dna\\getoriginal.py"
file:
  fnaPath: "C:\Guo\Git\gp-back\src\main\resources\Files"
