spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dna
    username: root
    password: mima
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

python:
  explainer:
    path: "C:\\Users\\silence\\miniconda3\\envs\\torch_1_13_1\\python.exe"
  script:
    path: "C:\\Users\\silence\\Desktop\\test.py"
file:
  storagePath: "C:\\Users\\silence\\Desktop\\Files"
